name: Build macOS App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build the application
      run: |
        pyinstaller --noconfirm --onefile --windowed \
          --name "FileSharer" \
          --add-data "app/style:app/style" \
          --add-data "app/ui:app/ui" \
          --hidden-import="PySide6.QtXml" \
          app/main.py

    - name: Create DMG
      run: |
        brew install create-dmg
        mkdir -p dist/dmg
        cp -r "dist/FileSharer.app" dist/dmg/
        create-dmg \
          --volname "FileSharer" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "FileSharer.app" 175 120 \
          --app-drop-link 425 120 \
          "dist/FileSharer.dmg" \
          "dist/dmg/"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: FileSharer-macOS
        path: |
          dist/FileSharer
          dist/FileSharer.dmg